/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Jornadas;
import Modelo.JornadaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author deleo
 */
public class FormJornadas extends javax.swing.JFrame {
    JornadaDAO dao = new JornadaDAO();


    /**
     * Creates new form FormJornadas
     */
    public FormJornadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsertarjor = new javax.swing.JButton();
        btnBuscarjor = new javax.swing.JButton();
        btnActualizarjor = new javax.swing.JButton();
        btnEliminarjor = new javax.swing.JButton();
        btnLimpiarjor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodjor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomjor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsertarjor.setText("Insertar");
        btnInsertarjor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarjorActionPerformed(evt);
            }
        });

        btnBuscarjor.setText("Buscar");
        btnBuscarjor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarjorActionPerformed(evt);
            }
        });

        btnActualizarjor.setText("Actualizar");
        btnActualizarjor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarjorActionPerformed(evt);
            }
        });

        btnEliminarjor.setText("Eliminar");
        btnEliminarjor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarjorActionPerformed(evt);
            }
        });

        btnLimpiarjor.setText("Limpiar");
        btnLimpiarjor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarjorActionPerformed(evt);
            }
        });

        jLabel1.setText("Código Jornada:");

        jLabel2.setText("Nombre de la Jornada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomjor)
                            .addComponent(txtCodjor)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertarjor)
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscarjor)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarjor)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarjor)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarjor)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodjor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomjor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarjor)
                    .addComponent(btnBuscarjor)
                    .addComponent(btnActualizarjor)
                    .addComponent(btnEliminarjor)
                    .addComponent(btnLimpiarjor))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarjorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarjorActionPerformed
        // TODO add your handling code here:
        if (txtCodjor.getText().trim().isEmpty() || txtNomjor.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        return;
    }

    try {
        int codigo = Integer.parseInt(txtCodjor.getText());
        String nombre = txtNomjor.getText();

        Jornadas jornada = new Jornadas(codigo, nombre);
        dao.insertar(jornada);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El código debe ser numérico");
    }
   
    }//GEN-LAST:event_btnInsertarjorActionPerformed

    private void btnBuscarjorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarjorActionPerformed
        // TODO add your handling code here:
         if (txtCodjor.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Dato inválido: Ingrese un código");
    txtCodjor.requestFocus();
    return;
}

try {
    int codigo = Integer.parseInt(txtCodjor.getText());

    Jornadas jornada = dao.buscar(codigo);

    // 🔹 Si no existe en BD
    if (jornada == null) {
        JOptionPane.showMessageDialog(this, "No encontrado");
        txtNomjor.setText("");
    } else {
        txtNomjor.setText(jornada.getNombre());
    }

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Dato inválido: Solo números");
    txtCodjor.setText("");
    txtCodjor.requestFocus();
}

        
        
    }//GEN-LAST:event_btnBuscarjorActionPerformed

    private void btnActualizarjorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarjorActionPerformed
        // TODO add your handling code here:
        
        int codigo = Integer.parseInt(txtCodjor.getText());
String nombre = txtNomjor.getText();

Jornadas jornada = new Jornadas(codigo, nombre);
dao.actualizar(jornada);

JOptionPane.showMessageDialog(this, "Jornada actualizada");

        
    }//GEN-LAST:event_btnActualizarjorActionPerformed

    private void btnEliminarjorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarjorActionPerformed
        // TODO add your handling code here:
        if (txtCodjor.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Dato inválido: Ingrese un código");
    txtCodjor.requestFocus();
    return;
}

try {
    int codigo = Integer.parseInt(txtCodjor.getText());

    dao.eliminar(codigo);

    JOptionPane.showMessageDialog(this, "Jornada eliminada");

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Dato inválido: Solo números");
    txtCodjor.setText("");
    txtCodjor.requestFocus();
}

    }//GEN-LAST:event_btnEliminarjorActionPerformed

    private void btnLimpiarjorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarjorActionPerformed
        // TODO add your handling code here:
        txtCodjor.setText("");
    txtNomjor.setText("");

    txtCodjor.requestFocus(); // opcional, pone el cursor en Código
        
    }//GEN-LAST:event_btnLimpiarjorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJornadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarjor;
    private javax.swing.JButton btnBuscarjor;
    private javax.swing.JButton btnEliminarjor;
    private javax.swing.JButton btnInsertarjor;
    private javax.swing.JButton btnLimpiarjor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCodjor;
    private javax.swing.JTextField txtNomjor;
    // End of variables declaration//GEN-END:variables
}
